// ======================================================================
// \title  ManyChoicesArrayAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for ManyChoices array
// ======================================================================

#include "Fw/Types/Assert.hpp"
#include "Ref/TypeDemo/ManyChoicesArrayAc.hpp"

namespace Ref {

  // ----------------------------------------------------------------------
  // Constructors
  // ----------------------------------------------------------------------

  ManyChoices ::
    ManyChoices() :
      Serializable()
  {
    *this = Ref::ManyChoices(Ref::Choice::ONE);
  }

  ManyChoices ::
    ManyChoices(const ElementType (&a)[SIZE]) :
      Serializable()
  {
    *this = a;
  }

  ManyChoices ::
    ManyChoices(const ElementType& e) :
      Serializable()
  {
    *this = e;
  }

  ManyChoices ::
    ManyChoices(const std::initializer_list<ElementType>& il) :
      Serializable()
  {
    *this = il;
  }

  ManyChoices ::
    ManyChoices(const ManyChoices& obj) :
      Serializable()
  {
    *this = obj;
  }

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  ManyChoices::ElementType& ManyChoices ::
    operator[](const FwSizeType i)
  {
    FW_ASSERT(i < SIZE, static_cast<FwAssertArgType>(i), static_cast<FwAssertArgType>(SIZE));
    return this->elements[i];
  }

  const ManyChoices::ElementType& ManyChoices ::
    operator[](const FwSizeType i) const
  {
    FW_ASSERT(i < SIZE, static_cast<FwAssertArgType>(i), static_cast<FwAssertArgType>(SIZE));
    return this->elements[i];
  }

  ManyChoices& ManyChoices ::
    operator=(const ManyChoices& obj)
  {
    if (this != &obj) {
      for (FwSizeType index = 0; index < SIZE; index++) {
        this->elements[index] = obj.elements[index];
      }
    }
    return *this;
  }

  ManyChoices& ManyChoices ::
    operator=(const ElementType (&a)[SIZE])
  {
    for (FwSizeType index = 0; index < SIZE; index++) {
      this->elements[index] = a[index];
    }
    return *this;
  }

  ManyChoices& ManyChoices ::
    operator=(const std::initializer_list<ElementType>& il)
  {
    // Since we are required to use C++11, this has to be a runtime check
    // In C++14, it can be a static check
    FW_ASSERT(il.size() == SIZE, static_cast<FwAssertArgType>(il.size()), static_cast<FwAssertArgType>(SIZE));
    FwSizeType i = 0;
    for (const auto& e : il) {
      FW_ASSERT(i < SIZE, static_cast<FwAssertArgType>(i), static_cast<FwAssertArgType>(SIZE));
      this->elements[i] = e;
      i++;
    }
    return *this;
  }

  ManyChoices& ManyChoices ::
    operator=(const ElementType& e)
  {
    for (FwSizeType index = 0; index < SIZE; index++) {
      this->elements[index] = e;
    }
    return *this;
  }

  bool ManyChoices ::
    operator==(const ManyChoices& obj) const
  {
    for (FwSizeType index = 0; index < SIZE; index++) {
      if (!((*this)[index] == obj[index])) {
        return false;
      }
    }
    return true;
  }

  bool ManyChoices ::
    operator!=(const ManyChoices& obj) const
  {
    return !(*this == obj);
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const ManyChoices& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Public member functions
  // ----------------------------------------------------------------------

  Fw::SerializeStatus ManyChoices ::
    serializeTo(Fw::SerializeBufferBase& buffer) const
  {
    Fw::SerializeStatus status = Fw::FW_SERIALIZE_OK;
    for (FwSizeType index = 0; index < SIZE; index++) {
      status = buffer.serializeFrom((*this)[index]);
      if (status != Fw::FW_SERIALIZE_OK) {
        return status;
      }
    }
    return status;
  }

  Fw::SerializeStatus ManyChoices ::
    deserializeFrom(Fw::SerializeBufferBase& buffer)
  {
    Fw::SerializeStatus status = Fw::FW_SERIALIZE_OK;
    for (FwSizeType index = 0; index < SIZE; index++) {
      status = buffer.deserializeTo((*this)[index]);
      if (status != Fw::FW_SERIALIZE_OK) {
        return status;
      }
    }
    return status;
  }

  FwSizeType ManyChoices ::
    serializedSize() const
  {
    return SERIALIZED_SIZE;
  }

#if FW_SERIALIZABLE_TO_STRING

  void ManyChoices ::
    toString(Fw::StringBase& sb) const
  {
    // Clear the output string
    sb = "";

    // Array prefix
    if (sb.length() + 2 <= sb.maxLength()) {
      sb += "[ ";
    } else {
      return;
    }

    for (FwSizeType index = 0; index < SIZE; index++) {
      Fw::String tmp;
      this->elements[index].toString(tmp);

      FwSizeType size = tmp.length() + (index > 0 ? 2 : 0);
      if ((size + sb.length()) <= sb.maxLength()) {
        if (index > 0) {
          sb += ", ";
        }
        sb += tmp;
      } else {
        break;
      }
    }

    // Array suffix
    if (sb.length() + 2 <= sb.maxLength()) {
      sb += " ]";
    }
  }

#endif

}
